version: 2
updates:
  # NPM dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "spotify-insights-team"
    labels:
      - "🤖 dependabot"
      - "📦 dependencies"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      # Group React ecosystem updates
      react:
        patterns:
          - "react*"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"
      
      # Group testing dependencies
      testing:
        patterns:
          - "vitest*"
          - "@vitest/*"
          - "@testing-library/*"
          - "playwright*"
          - "jest*"
        update-types:
          - "minor"
          - "patch"
      
      # Group UI component libraries
      ui-components:
        patterns:
          - "@radix-ui/*"
          - "lucide-react"
          - "tailwind*"
          - "class-variance-authority"
        update-types:
          - "minor"
          - "patch"
      
      # Group build tools
      build-tools:
        patterns:
          - "vite*"
          - "@vitejs/*"
          - "eslint*"
          - "typescript*"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    labels:
      - "🤖 dependabot"
      - "🔧 github-actions"
    commit-message:
      prefix: "ci"
      include: "scope" 