name: 🐛 Bug Report
description: Report a bug to help us improve Spotify Insights
title: "[Bug]: "
labels: ["🐛 bug", "🔍 triage"]
projects: ["spotify-insights"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🙏
        
        Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 🔄 Steps to Reproduce
      description: How do we trigger this bug? Please walk us through it step by step.
      placeholder: |
        1. Go to...
        2. Click on...
        3. Scroll down to...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: What should have happened?
      placeholder: Describe the expected outcome
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually occurred
    validations:
      required: true

  - type: dropdown
    id: bug-severity
    attributes:
      label: 🚨 Bug Severity
      description: How severe is this bug?
      options:
        - 🔴 Critical (blocks core functionality)
        - 🟠 High (major feature broken)
        - 🟡 Medium (minor feature issue)
        - 🟢 Low (cosmetic/minor issue)
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: 🌐 Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Opera
        - Other
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: 🔢 Browser Version
      description: What version of the browser are you using?
      placeholder: e.g., Chrome 119.0.6045.105

  - type: dropdown
    id: operating-system
    attributes:
      label: 💻 Operating System
      description: What OS are you using?
      options:
        - Windows 11
        - Windows 10
        - macOS Ventura
        - macOS Monterey
        - macOS Big Sur
        - Ubuntu
        - Other Linux
        - iOS
        - Android
    validations:
      required: true

  - type: dropdown
    id: device-type
    attributes:
      label: 📱 Device Type
      description: What device are you using?
      options:
        - Desktop
        - Laptop
        - Tablet
        - Mobile Phone
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: 👤 User Type
      description: What type of user are you?
      options:
        - 🎵 Allowlisted Spotify user
        - 🎮 Sandbox mode user
        - 🔧 Developer/Contributor
    validations:
      required: true

  - type: textarea
    id: console-errors
    attributes:
      label: 🖥️ Console Errors
      description: Are there any errors in the browser console?
      placeholder: |
        Right-click → Inspect → Console tab
        Copy any error messages here
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop or paste screenshots here

  - type: textarea
    id: additional-context
    attributes:
      label: 📋 Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful

  - type: checkboxes
    id: troubleshooting
    attributes:
      label: 🔧 Troubleshooting Steps Tried
      description: Have you tried any of these troubleshooting steps?
      options:
        - label: Hard refresh (Ctrl+F5 / Cmd+Shift+R)
        - label: Cleared browser cache and cookies
        - label: Tried in incognito/private mode
        - label: Tested in a different browser
        - label: Checked network connection
        - label: Tried logging out and back in

  - type: checkboxes
    id: terms
    attributes:
      label: ✅ Confirmation
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all the requested information
          required: true
        - label: I understand this is for bug reports only (not feature requests)
          required: true 